name: Install
description: Install and cache deps

runs:
  using: composite
  steps:
    - name: Use pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Use nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
