name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo under GH workspace
      uses: actions/checkout@v4

    - name: Install
      uses: ./.github/actions/install

    - name: Run the CI script
      run: pnpm run ci

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
