name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.nix'
      - '.all-contributorsrc'
      - '.vscode/**'
      - 'Dockerfile'
      - 'LICENSE'
      - 'compose.yml'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo under GH workspace
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install
        uses: ./.github/actions/install

      - name: Run the CI script
        run: pnpm run ci

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
